# Generated by Django 4.0.1 on 2022-01-29 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('darkChoco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='from_user',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='letter',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
